# Generated by Django 3.0.8 on 2020-07-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Course_Num',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
