# Generated by Django 3.0.8 on 2020-07-18 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_auto_20200717_1908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='djangoClasses',
        ),
    ]
